name: Java CI

on:  
  push:
    branches:
      - basic-editing-feature
  pull_request:
    branches:
      - basic-editing-feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file JHotDraw/pom.xml

  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run tests with Maven
        run: mvn -B test --file ../JHotDraw/pom.xml